name: brisk_deals
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.4
  lottie: ^2.2.0
  email_validator: ^2.0.1
  google_nav_bar: ^5.0.6
  google_fonts: ^3.0.1
  curved_navigation_bar: ^1.0.3
  flutter_screenutil: ^5.6.0
  google_sign_in: ^5.4.4
  flutter_bloc: ^8.1.1
  http: ^0.13.5
  hive_flutter: ^1.1.0
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  animated_splash_screen: ^1.3.0
  page_transition: ^2.0.9
  intl: ^0.18.0
  fluttertoast: ^8.2.1
  dropdownfield2: ^1.0.7
  khalti_flutter: ^2.2.1
  share_plus: ^6.3.1
  screenshot: ^1.3.0
  path_provider: ^2.0.14
  dcdg: ^4.1.0
  internet_connection_checker: ^0.0.1+4
  connectivity_plus: ^2.3.6+1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0


flutter:

  
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/images/google.svg
      - assets/images/logo.svg
      - assets/images/splashscreen.svg
      - assets/images/pizzas.png
      - assets/images/profile.jpeg
      - assets/images/image.jpg
      - assets/lottie/welcome.json
      - assets/images/logo2.svg
      - assets/lottie/mail.json
      - assets/lottie/location.json
      - assets/lottie/loading.json
      - assets/lottie/forgetpwMail.json
      - assets/lottie/getDiscount.json
      - assets/lottie/growBusiness.json
      - assets/lottie/growBusiness2.json
      - assets/lottie/Search.json
      - assets/lottie/adddeals.json
      - assets/lottie/search_empty.json
      - assets/lottie/noDealsFound.json
      - assets/images/animationPNG.png
      - assets/images/swimming.png
      - assets/images/servicing.png
      - assets/images/health.png


      


